### ISSUE TITLE
Docker version Works perfectly fine, but Go build from master branch only works on No TLS

### ISSUE THREAD

**Issue by polarbroadband** [karimra/gnmic#371]
the certificate verification seems good (tried both skip verification and provide CA certification), but dial state stuck in transient failure, reporting error "connection closed".

The docker version is good though with the same config.

**Comment by karimra** [comment]
This could be related to the go version you are using to build your binary.

Go dropped [NPN](https://tools.ietf.org/id/draft-agl-tls-nextprotoneg-03.html) support in 1.14, rightfully so. [ALPN](https://tools.ietf.org/html/rfc7301) should be used. 

Some routers TLS implementations still use NPN, that's why gnmic is still built with go1.13

**Comment by polarbroadband** [comment]
You are absolutely right, I changed the building environment to go 1.13 and it fixed.

I did notice the difference from tcpdump, but should use the wireshark to check the details.

This makes GNMIC a viable tool to communicate with these "old" routers and push the results to its subscribers which are built in latest Go version.

Great thanks!
