### ISSUE TITLE
Adding target through API does not start subscribing to that target

### ISSUE THREAD

**Issue by dshah2012** [karimra/gnmic#424]
Hello @karimra ,

I was also looking other ways of adding targets to gnmic config and one method was 
First: I used was the target file loader which worked fine. 
Second one I was experimenting with respect to the API. 
I was using this end point to add targets.
https://gnmic.kmrd.dev/user_guide/api/configuration/#post-configtargets .
I was able to successfully add the target as i was able to see in the get config API. 
It did not start subscribing to the new targets that was added through API.

For example: 
I have done the POST with this body that has a new target device.
`{"address": "target_ip_address:57400", "username": "username", "password": "password", "insecure": true, "subscriptions":["subscription_name"], "outputs": ["output_name"]}`

When I looked into the config I was able to see the target that I have added under target section of the full config that we receive from the get config API.

```
"targets": {
        "": {
            "address": "target_ip_address:57400",
            "username": "username",
            "password": "password",
            "insecure": true,
            "subscriptions": [
                "subscription_name"
            ],
            "outputs": [
                "output_name"
            ],
            "buffer-size": 1000,
            "retry-timer": 10000000000
        }
}
```

There was one thing odd that i saw is that the target key is empty for that new target that was added through API. Not sure because of this its not subscribing to the new target,?
I can see in the logs the addition of new target through API.
One of the other issue I see is that after doing an first POST with new target. I am not able to use the POST again to add one more. It redirects to the GET method not sure if this expected .
```
10.42.36.0 - - [19/Jul/2021:20:56:58 +0000] "POST /config/targets/ HTTP/1.1" 301 0
10.42.36.0 - - [19/Jul/2021:20:56:58 +0000] "GET /config/targets HTTP/1.1" 200 310
```

**Comment by karimra** [comment]
Hi @dshah2012,

The key is missing because the request body is missing `name`.
I will update the docs example and either make the name mandatory through the API or make it default to `address`

To start the subscriptions for a newly added target you can use this endpoint: https://gnmic.kmrd.dev/user_guide/api/targets/#post-targetsid
The `id` should be the value in `name` from the added config.

As for the redirect, it could be because of adding a target with the same name ( empty string )

Please note that this API is meant to enable `gnmic` clustering, I don't consider it to be very robust at this point.

**Comment by dshah2012** [comment]
Okay Thanks
